name: test_suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite
        run: make test
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite
        run: make test
